image: decentraland/ci-node:latest

build:
  script:
    - ./setupEnv.sh
    - npm install && npm run build
    - dcl-lock-sync
    - cd .ci && npm install && dcl-up website-builder
    - dcl-sync-release && cd ..
    - dcl-upload build
    - cd .ci && dcl-cache-invalidation
