image: decentraland/ci-node:latest

build:
  only:
    - master
    - staging
    - release
  script:
    - ./setupEnv.sh
    - export NODE_OPTIONS="--max-old-space-size=8192"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - npm ci && npm run build
    - dcl-lock-sync
    - cd .ci && npm install && dcl-up website-builder
    - dcl-sync-release && cd ..
    - dcl-upload build
    - cd .ci && dcl-cache-invalidation
